# Generated by Django 4.2.3 on 2024-07-18 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_balance",
                    models.PositiveIntegerField(default=0, verbose_name="Số dư ví"),
                ),
                ("previous_balance", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng",
                    ),
                ),
            ],
            options={"verbose_name": "Ví", "verbose_name_plural": "Ví",},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True, default=0, verbose_name="Số tiền"
                    ),
                ),
                (
                    "return_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("00", "Thành công"),
                            ("01", "Thất bại"),
                            ("02", "Chờ xử lý"),
                        ],
                        default="02",
                        max_length=2,
                        null=True,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "funds",
                    models.CharField(
                        blank=True,
                        choices=[("OCCO", "Thóc"), ("Appota", "Appota")],
                        default="00",
                        max_length=10,
                        null=True,
                        verbose_name="Nguồn tiền",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("deposit", "Mua thóc"),
                            ("withdraw", "Rút tiền"),
                            ("gift", "Tặng quà"),
                        ],
                        default="DEPOSIT",
                        max_length=50,
                        null=True,
                        verbose_name="Loại giao dịch",
                    ),
                ),
                ("information_detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_from",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người tạo",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người nhận",
                    ),
                ),
            ],
        ),
    ]
