# Generated by Django 4.2.3 on 2024-07-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="funds",
            field=models.CharField(
                blank=True,
                choices=[("Coin", "Thóc"), ("Appota", "Appota")],
                default="00",
                max_length=10,
                null=True,
                verbose_name="Nguồn tiền",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("deposit", "Mua thóc"), ("withdraw", "Rút tiền")],
                default="DEPOSIT",
                max_length=50,
                null=True,
                verbose_name="Loại giao dịch",
            ),
        ),
    ]
