# Generated by Django 4.2.3 on 2024-07-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_transaction_funds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("deposit", "Mua thóc"), ("withdraw", "Rút thóc")],
                default="deposit",
                max_length=50,
                null=True,
                verbose_name="Loại giao dịch",
            ),
        ),
    ]
