# Generated by Django 4.2.3 on 2024-07-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Giao dịch", "verbose_name_plural": "Giao dịch"},
        ),
    ]
