# Generated by Django 4.2.3 on 2024-08-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0009_transaction_appota_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deposit", "Mua thóc"),
                    ("uid", "Mua id"),
                    ("avatar", "Mua khung avatar"),
                    ("gift", "Mua quà"),
                    ("withdraw", "Rút thóc"),
                ],
                default="deposit",
                max_length=50,
                null=True,
                verbose_name="Loại giao dịch",
            ),
        ),
    ]
