# Generated by Django 4.2.3 on 2024-08-02 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "bin_card",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=256, null=True)),
                ("is_disburse", models.BooleanField(default=False)),
                ("is_napas", models.BooleanField(default=False)),
                ("is_viet_pr", models.BooleanField(default=False)),
                (
                    "fullname",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tên ngân hàng"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        unique=True,
                        verbose_name="Tên rút gọn",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assets/bank-icon",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật"),
                ),
            ],
            options={"verbose_name": "Ngân hàng", "verbose_name_plural": "Ngân hàng",},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deposit", "Mua thóc"),
                    ("uid", "Mua id"),
                    ("avatar", "Mua khung avatar"),
                    ("gift", "Mua quà"),
                    ("withdraw", "Rút thóc"),
                    ("coinToAds", "Quảng bá"),
                ],
                default="deposit",
                max_length=50,
                null=True,
                verbose_name="Loại giao dịch",
            ),
        ),
    ]
