# Generated by Django 4.2.3 on 2024-05-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0015_report_fk_id_report_note_alter_report_type"),
        ("user", "0026_reportmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cover_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cover_image",
                to="general.fileupload",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="avatar",
                to="general.fileupload",
            ),
        ),
    ]
