# Generated by Django 4.2.3 on 2024-05-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_customuser_cover_image_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="uid",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
