# Generated by Django 4.2.3 on 2024-05-15 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_customuser_uid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportmessage",
            options={
                "verbose_name": "Vi phạm tin nhắn",
                "verbose_name_plural": "Vi phạm tin nhắn",
            },
        ),
        migrations.AlterField(
            model_name="reportmessage",
            name="banned_to",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bị cấm đến"
            ),
        ),
        migrations.AlterField(
            model_name="reportmessage",
            name="count",
            field=models.IntegerField(default=0, verbose_name="Số lần"),
        ),
        migrations.AlterField(
            model_name="reportmessage",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người vi phạm",
            ),
        ),
    ]
