# Generated by Django 4.2.3 on 2024-05-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_alter_reportmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profileimage",
            options={
                "verbose_name": "Ảnh profile",
                "verbose_name_plural": "Ảnh profile",
            },
        ),
    ]
