# Generated by Django 4.2.3 on 2024-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0030_alter_profileimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="social",
            field=models.JSONField(default=dict),
        ),
    ]
