# Generated by Django 4.2.3 on 2024-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_alter_customuser_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("REGISTER", "Đăng ký"), ("PASSWORD", "Quên mật khẩu")],
                max_length=8,
                null=True,
            ),
        ),
    ]
