# Generated by Django 4.2.3 on 2024-07-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_alter_customuser_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Có quyền truy cập"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_fake",
            field=models.BooleanField(default=False, verbose_name="Người dùng ảo"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="province",
            field=models.CharField(
                blank=True,
                default="Hồ Chí Minh",
                max_length=50,
                null=True,
                verbose_name="Tỉnh thành",
            ),
        ),
    ]
