# Generated by Django 4.2.3 on 2024-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_alter_customuser_is_active_alter_customuser_is_fake_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vietnam", "Việt Nam"),
                    ("Laos", "Lào"),
                    ("Cambodia", "Cambodia"),
                    ("All", "Tất cả"),
                ],
                default="Vietnam",
                max_length=50,
                null=True,
                verbose_name="Quốc gia",
            ),
        ),
    ]
