# Generated by Django 4.2.3 on 2024-07-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_alter_customuser_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100, unique=True)),
                ("phone_number", models.CharField()),
                ("info", models.JSONField(default=list)),
                ("login", models.JSONField(default=list)),
                ("logout", models.JSONField(default=list)),
                ("blog", models.JSONField(default=list)),
                ("live", models.JSONField(default=list)),
                ("comment", models.JSONField(default=list)),
            ],
        ),
    ]
