# Generated by Django 4.2.3 on 2024-07-18 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_userlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_upload_idcard",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="IDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_front_image",
                    models.ImageField(
                        null=True, upload_to="assets/id-card/front-image/"
                    ),
                ),
                (
                    "id_back_image",
                    models.ImageField(
                        null=True, upload_to="assets/id-card/back-image/"
                    ),
                ),
                (
                    "id_full_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_gender",
                    models.CharField(
                        choices=[("male", "Nam"), ("female", "Nữ")],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "id_identifier",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_date_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_date_issuance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "id_place_of_residence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="id_card",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
