# Generated by Django 4.2.3 on 2024-07-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_customuser_is_private_customuser_is_upload_idcard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idcard",
            name="id_gender",
            field=models.CharField(
                choices=[("male", "Nam"), ("female", "Nữ")], max_length=7, null=True
            ),
        ),
    ]
