# Generated by Django 4.2.3 on 2024-07-18 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0040_alter_idcard_id_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="idcard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="idcard",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
