# Generated by Django 4.2.3 on 2024-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0041_idcard_created_at_idcard_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="notification_mode",
            field=models.CharField(
                choices=[
                    ("on", "Bật thông báo"),
                    ("off23to6", "Tắt 23h đến 6h"),
                    ("off", "Tắt thông báo"),
                ],
                default="on",
            ),
        ),
    ]
