# Generated by Django 4.2.3 on 2024-07-20 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0042_customuser_notification_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="idcard",
            name="id_face_image",
            field=models.ImageField(null=True, upload_to="assets/id-card/face-image/"),
        ),
        migrations.AddField(
            model_name="idcard", name="note", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="idcard",
            name="status_verify",
            field=models.CharField(
                choices=[
                    ("pending", "Đợi duyệt"),
                    ("verified", "Đã duyệt"),
                    ("rejected", "Đã từ chối"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AddField(
            model_name="idcard",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idcard",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
