# Generated by Django 4.2.3 on 2024-07-20 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_idcard_id_face_image_idcard_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idcard",
            options={"verbose_name": "CCCD", "verbose_name_plural": "CCCD"},
        ),
        migrations.AlterField(
            model_name="idcard",
            name="status_verify",
            field=models.CharField(
                choices=[
                    ("start", "Chưa nộp"),
                    ("pending", "Đợi duyệt"),
                    ("verified", "Đã duyệt"),
                    ("rejected", "Đã từ chối"),
                ],
                default="start",
                max_length=10,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="idcard",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="id_verified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Duyệt bởi",
            ),
        ),
    ]
