# Generated by Django 4.2.3 on 2024-07-25 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0045_customuser_avatar_frame_alter_customuser_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("COMMENT", "COMMENT"), ("LIKE", "LIKE")],
                        default="",
                        max_length=50,
                    ),
                ),
                ("title", models.TextField(max_length=80, verbose_name="Tiêu đề")),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="Nội dung"),
                ),
                ("link", models.CharField(default="/admin", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timeline",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người dùng tạo thông báo",
                    ),
                ),
            ],
        ),
    ]
