# Generated by Django 4.2.3 on 2024-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0046_usertimeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertimeline",
            name="fk_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
