# Generated by Django 4.2.3 on 2024-07-30 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0047_usertimeline_fk_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertimeline",
            name="direct_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_timeline",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người liên quan",
            ),
        ),
    ]
