# Generated by Django 4.2.3 on 2024-08-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0049_customuser_setting_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="platform",
            field=models.CharField(
                choices=[("ANDROID", "ANDROID"), ("IOS", "IOS")],
                default="ANDROID",
                max_length=10,
            ),
        ),
    ]
