# Generated by Django 4.2.3 on 2024-08-05 10:02

import apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0037_vip_alter_appinformation_title_and_more"),
        ("user", "0051_historyseen"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="setting_vip",
            field=models.JSONField(default=apps.user.models.init_vip),
        ),
        migrations.CreateModel(
            name="UserVip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True)),
                ("date_end", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vip",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vip",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="general.vip",
                    ),
                ),
            ],
        ),
    ]
