# Generated by Django 4.2.3 on 2024-05-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0015_liveuser_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="view",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
