# Generated by Django 4.2.3 on 2024-05-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0016_alter_livestreaminghistory_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="title_en",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="title_vi",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="country",
            field=models.CharField(
                choices=[("VI", "Việt Nam"), ("--", "--")], default="--", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="side",
            field=models.CharField(
                choices=[
                    ("NORTH", "Miền bắc"),
                    ("CENTRAL", "Miền trung"),
                    ("SOUTH", "Miền nam"),
                    ("ALL", "Toàn quốc"),
                ],
                default="--",
                max_length=255,
            ),
        ),
    ]
