# Generated by Django 4.2.3 on 2024-05-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0017_gift_title_en_gift_title_vi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="country",
            field=models.CharField(
                choices=[("VI", "Việt Nam"), ("--", "--")], max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="side",
            field=models.CharField(
                choices=[
                    ("NORTH", "Miền bắc"),
                    ("CENTRAL", "Miền trung"),
                    ("SOUTH", "Miền nam"),
                    ("ALL", "Toàn quốc"),
                ],
                max_length=255,
            ),
        ),
    ]
