# Generated by Django 4.2.3 on 2024-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0019_alter_livestreaminghistory_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="max_chairs",
            field=models.IntegerField(default=1),
        ),
    ]
