# Generated by Django 4.2.3 on 2024-05-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0021_livestreaminghistory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftlog",
            name="live_streaming",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discovery.livestreaminghistory",
            ),
        ),
    ]
