# Generated by Django 4.2.3 on 2024-05-09 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discovery", "0024_liveuser_is_live_alter_messagelive_created_at_emoji"),
    ]

    operations = [
        migrations.RemoveField(model_name="emoji", name="live",),
        migrations.RemoveField(model_name="emoji", name="sender",),
        migrations.CreateModel(
            name="EmojiLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emoji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.emoji",
                    ),
                ),
                (
                    "live",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.livestreaminghistory",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
