# Generated by Django 4.2.3 on 2024-05-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0025_remove_emoji_live_remove_emoji_sender_emojilog"),
    ]

    operations = [
        migrations.AddField(
            model_name="emoji", name="name", field=models.CharField(default=""),
        ),
    ]
