# Generated by Django 4.2.3 on 2024-05-09 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discovery", "0026_emoji_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="giftlog", name="receiver",),
        migrations.AddField(
            model_name="giftlog",
            name="receiver",
            field=models.ManyToManyField(
                related_name="receiver_gift", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
