# Generated by Django 4.2.3 on 2024-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0027_remove_giftlog_receiver_giftlog_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
