# Generated by Django 4.2.3 on 2024-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0028_livestreaminghistory_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveAudioProxy",
            fields=[],
            options={
                "verbose_name": "Phòng chat",
                "verbose_name_plural": "Phòng chat",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("discovery.livestreaminghistory",),
        ),
        migrations.CreateModel(
            name="LiveChatProxy",
            fields=[],
            options={
                "verbose_name": "Phòng chat",
                "verbose_name_plural": "Phòng chat",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("discovery.livestreaminghistory",),
        ),
        migrations.CreateModel(
            name="LiveVideoProxy",
            fields=[],
            options={
                "verbose_name": "Phòng chat",
                "verbose_name_plural": "Phòng chat",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("discovery.livestreaminghistory",),
        ),
    ]
