# Generated by Django 4.2.3 on 2024-05-15 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0029_liveaudioproxy_livechatproxy_livevideoproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="liveaudioproxy",
            options={
                "verbose_name": "Phòng Voice",
                "verbose_name_plural": "Phòng Voice",
            },
        ),
        migrations.AlterModelOptions(
            name="livechatproxy",
            options={"verbose_name": "Phòng Chat", "verbose_name_plural": "Phòng Chat"},
        ),
        migrations.AlterModelOptions(
            name="livevideoproxy",
            options={
                "verbose_name": "Phòng Video",
                "verbose_name_plural": "Phòng Video",
            },
        ),
    ]
