# Generated by Django 4.2.3 on 2024-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0031_alter_liveuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emoji",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
