# Generated by Django 4.2.3 on 2024-05-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0032_alter_emoji_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="banneduser",
            name="live_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discovery.liveuser",
            ),
        ),
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="max_chairs",
            field=models.IntegerField(default=12),
        ),
    ]
