# Generated by Django 4.2.3 on 2024-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0036_alter_livestreaminghistory_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="liveuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
