# Generated by Django 4.2.3 on 2024-06-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0037_livestreaminghistory_is_active_liveuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAT", "Chat"),
                    ("AUDIO", "Audio"),
                    ("VIDEO", "Video"),
                    ("STREAM", "Stream"),
                ],
                max_length=6,
                null=True,
                verbose_name="Loại phòng",
            ),
        ),
    ]
