# Generated by Django 4.2.3 on 2024-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0038_alter_livestreaminghistory_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="view",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
