# Generated by Django 4.2.3 on 2024-07-06 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discovery", "0039_alter_livestreaminghistory_view"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gift",
            options={"verbose_name": "Quà tặng", "verbose_name_plural": "Quà tặng"},
        ),
        migrations.RemoveField(model_name="gift", name="type",),
        migrations.RemoveField(model_name="liveuser", name="agora_uid",),
        migrations.AddField(
            model_name="giftlog",
            name="add_info",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="livestreaminghistory",
            name="agora_token",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="liveuser",
            name="agora_token",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="gift",
            name="image",
            field=models.ImageField(
                upload_to="assets/image/gift", verbose_name="Ảnh quà tặng"
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Giá"),
        ),
        migrations.AlterField(
            model_name="gift",
            name="title",
            field=models.CharField(max_length=15, verbose_name="Tên"),
        ),
        migrations.AlterField(
            model_name="gift",
            name="title_en",
            field=models.CharField(max_length=15, null=True, verbose_name="Tên"),
        ),
        migrations.AlterField(
            model_name="gift",
            name="title_vi",
            field=models.CharField(max_length=15, null=True, verbose_name="Tên"),
        ),
        migrations.AlterField(
            model_name="giftlog",
            name="gift",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discovery.gift",
            ),
        ),
        migrations.AlterField(
            model_name="giftlog",
            name="live_streaming",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discovery.livestreaminghistory",
            ),
        ),
        migrations.AlterField(
            model_name="giftlog",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sender_gift",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
