# Generated by Django 4.2.3 on 2024-07-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0040_alter_gift_options_remove_gift_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStreamProxy",
            fields=[],
            options={
                "verbose_name": "Livestream",
                "verbose_name_plural": "Livestream",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("discovery.livestreaminghistory",),
        ),
        migrations.AlterField(
            model_name="giftlog", name="add_info", field=models.JSONField(default=dict),
        ),
    ]
