# Generated by Django 4.2.3 on 2024-07-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0041_livestreamproxy_alter_giftlog_add_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="is_stopped",
            field=models.BooleanField(default=False),
        ),
    ]
