# Generated by Django 4.2.3 on 2024-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0042_livestreaminghistory_is_stopped"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="agora_user_token",
            field=models.TextField(default=""),
        ),
    ]
