# Generated by Django 4.2.3 on 2024-07-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0043_livestreaminghistory_agora_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
    ]
