# Generated by Django 4.2.3 on 2024-07-18 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discovery", "0044_alter_livestreaminghistory_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveuser",
            name="is_on_mic",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="UserGift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="discovery.gift"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
