# Generated by Django 4.2.3 on 2024-07-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0030_sticker"),
        ("discovery", "0045_liveuser_is_on_mic_usergift"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagelive",
            name="sticker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="general.sticker",
            ),
        ),
        migrations.AlterField(
            model_name="messagelive",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEXT", "Văn bản"),
                    ("AUDIO", "Âm thanh"),
                    ("VIDEO", "Video"),
                    ("IMAGE", "Hình ảnh"),
                    ("FILE", "File"),
                    ("GIFT", "Quà tặng"),
                    ("CALL", "Gọi"),
                    ("VIDEO_CALL", "Gọi"),
                    ("HISTORY", "Lịch sử"),
                    ("STICKER", "Nhãn dán"),
                ],
                max_length=10,
                null=True,
                verbose_name="Loại",
            ),
        ),
    ]
