# Generated by Django 4.2.3 on 2024-07-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0046_messagelive_sticker_alter_messagelive_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftlog",
            options={
                "verbose_name": "Lịch sử tặng quà",
                "verbose_name_plural": "Lịch sử tặng quà",
            },
        ),
    ]
