# Generated by Django 4.2.3 on 2024-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0047_alter_giftlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftlog",
            name="place",
            field=models.CharField(
                choices=[("LIVE", "Live"), ("CHAT", "Phòng chat")],
                default="LIVE",
                max_length=20,
            ),
        ),
    ]
