# Generated by Django 4.2.3 on 2024-08-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0048_giftlog_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="id_show",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="ID Hiển thị",
            ),
        ),
    ]
