# Generated by Django 4.2.3 on 2024-05-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Interaction",),
    ]
