# Generated by Django 4.2.3 on 2024-07-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notificationadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='link',
            field=models.CharField(default='/admin', max_length=1000),
        ),
    ]
