# Generated by Django 4.2.3 on 2024-07-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_notificationadmin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_admin', to=settings.AUTH_USER_MODEL, verbose_name='Thông báo cho admin'),
        ),
        migrations.AlterField(
            model_name='notificationadmin',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_admin_user', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng tạo thông báo'),
        ),
    ]
