# Generated by Django 4.2.3 on 2024-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notificationadmin_admin_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='type',
            field=models.CharField(choices=[('COMMENT', 'COMMENT'), ('LIKE', 'LIKE'), ('REFLECT', 'REFLECT'), ('NEW', 'NEW')], default='', max_length=50),
        ),
    ]
