# Generated by Django 4.2.3 on 2024-06-16 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_blog_user_like_comment_user_like_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "Bài đăng", "verbose_name_plural": "Bài đăng"},
        ),
        migrations.AddField(
            model_name="blog",
            name="is_highlight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blog",
            name="location_point",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Nội dung"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="count_comment",
            field=models.PositiveIntegerField(default=0, verbose_name="Tổng comment"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="count_like",
            field=models.PositiveIntegerField(default=0, verbose_name="Tổng like"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="count_share",
            field=models.PositiveIntegerField(default=0, verbose_name="Tổng share"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Hiển thị"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="location",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Vị trí"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tagged_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="tagged_in",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gắn thẻ",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người đăng",
            ),
        ),
    ]
