# Generated by Django 4.2.3 on 2024-06-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_audioupload_blog_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioupload",
            name="file",
            field=models.FileField(upload_to="assets/blog/audio"),
        ),
    ]
