# Generated by Django 4.2.3 on 2024-07-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_audioupload_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audioupload",
            options={
                "verbose_name": "Âm thanh bài đăng",
                "verbose_name_plural": "Âm thanh bài đăng",
            },
        ),
        migrations.AlterField(
            model_name="audioupload",
            name="index",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Vị trí hiển thị"
            ),
        ),
        migrations.AlterField(
            model_name="audioupload",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tên hiển thị"
            ),
        ),
    ]
