# Generated by Django 4.2.3 on 2024-07-25 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0009_alter_audioupload_options_alter_audioupload_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="hide_by",
            field=models.ManyToManyField(
                related_name="hide_blog", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
