# Generated by Django 4.2.3 on 2024-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0018_alter_message_created_at_alter_room_newest_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ManyToManyField(default=list, to="conversation.roomuser"),
        ),
        migrations.AddField(
            model_name="message",
            name="is_revoked",
            field=models.BooleanField(default=False),
        ),
    ]
