# Generated by Django 4.2.3 on 2024-05-10 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversation", "0019_message_deleted_by_message_is_revoked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="deleted_by",
            field=models.ManyToManyField(
                default=list, related_name="deleted_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
