# Generated by Django 4.2.3 on 2024-05-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0020_alter_message_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="last_message",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="roomuser",
            name="total_unseen",
            field=models.IntegerField(default=0),
        ),
    ]
