# Generated by Django 4.2.3 on 2024-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0021_roomuser_last_message_roomuser_total_unseen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Tin nhắn", "verbose_name_plural": "Tin nhắn"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Tin nhắn", "verbose_name_plural": "Tin nhắn"},
        ),
        migrations.AlterModelOptions(
            name="roomuser",
            options={"verbose_name": "Thành viên", "verbose_name_plural": "Thành viên"},
        ),
        migrations.AddField(
            model_name="privatequeue",
            name="is_stop",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="randomqueue",
            name="is_stop",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Gửi vào"
            ),
        ),
        migrations.AlterField(
            model_name="roomuser",
            name="last_message",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
