# Generated by Django 4.2.3 on 2024-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0022_alter_message_options_alter_room_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="title",),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RANDOM", "Ngẫu nhiên"),
                    ("PRIVATE", "Ẩn danh"),
                    ("CONNECT", "Thông thường"),
                    ("GROUP", "Nhóm"),
                ],
                max_length=12,
                null=True,
                verbose_name="Loại phòng",
            ),
        ),
    ]
