# Generated by Django 4.2.3 on 2024-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0026_alter_message_text_alter_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RANDOM", "Ngẫu nhiên"),
                    ("PRIVATE", "Ẩn danh"),
                    ("CONNECT", "Thông thường"),
                    ("GROUP", "Nhóm"),
                    ("CSKH", "Chăm sóc khách hàng"),
                ],
                max_length=12,
                null=True,
                verbose_name="Loại phòng",
            ),
        ),
    ]
