# Generated by Django 4.2.3 on 2024-06-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0027_alter_room_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
