# Generated by Django 4.2.3 on 2024-07-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0028_roomuser_is_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
