# Generated by Django 4.2.3 on 2024-07-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0024_alter_backgroundcolor_color_and_more"),
        ("conversation", "0032_seenbymessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="background_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="general.backgroundcolor",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="background",
                to="general.fileupload",
            ),
        ),
    ]
