# Generated by Django 4.2.3 on 2024-07-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0030_sticker"),
        ("conversation", "0034_message_location_alter_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sticker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="general.sticker",
            ),
        ),
    ]
