# Generated by Django 4.2.3 on 2024-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0036_alter_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="block_2_user",
            field=models.CharField(
                blank=True,
                choices=[("BLOCK", "Chặn"), ("BLOCKED", "Bị chặn")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="roomuser",
            name="notification_mode",
            field=models.CharField(
                choices=[("on", "Bật"), ("off", "Tắt")], default="on"
            ),
        ),
    ]
