# Generated by Django 4.2.3 on 2024-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0038_remove_room_block_2_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="block_status_private",
            field=models.CharField(
                blank=True,
                choices=[("BLOCK", "Chặn"), ("BLOCKED", "Bị chặn")],
                null=True,
            ),
        ),
    ]
