# Generated by Django 4.2.3 on 2024-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0040_message_style_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="newest_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Tin nhắn cuối vào"
            ),
        ),
    ]
