# Generated by Django 4.2.3 on 2024-07-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0048_giftlog_place"),
        ("conversation", "0042_alter_pinnedmessage_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="gift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discovery.giftlog",
            ),
        ),
    ]
