version: '3'

services:
  app:
    build: .
    ports:
      - "8006:8000"
    environment:
      - CELERY_BROKER_URL=amqp://cydeva:Cydeva@2024@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/3
      - CACHE_REDIS_URL=redis://redis:6379/4
      - SOCKET_REDIS_URL=redis://redis:6379/1
    depends_on:
      - rabbitmq
      - redis
    command: ["sh", "-c", "sleep 5 && supervisord -n"]

  redis:
    image: redis:latest
    command: >
      redis-server 
      --tcp-backlog 511 
      --tcp-keepalive 300 
      --maxmemory 2gb 
      --maxmemory-policy allkeys-lru 
      --appendfsync everysec 
      --hz 10 
      --loglevel notice 
      --logfile "" 
      --databases 16

  rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: cydeva
        RABBITMQ_DEFAULT_PASS: Cydeva@2024
      healthcheck:
        test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 5