# Generated by Django 4.2.3 on 2024-05-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0014_rename_video_duration_fileupload_file_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="fk_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="note",
            field=models.CharField(default="", verbose_name="Lí do duyệt"),
        ),
        migrations.AlterField(
            model_name="report",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MESSAGE", "Tin nhắn"),
                    ("BLOG", "Bài viết"),
                    ("LIVE", "Live"),
                ],
                max_length=7,
                null=True,
                verbose_name="Loại",
            ),
        ),
    ]
