# Generated by Django 4.2.3 on 2024-05-15 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0015_report_fk_id_report_note_alter_report_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="feedback", name="title",),
        migrations.RemoveField(model_name="feedback", name="user",),
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedback",
            name="full_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Họ tên"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="is_resolve",
            field=models.BooleanField(default=False, verbose_name="Đã xử lý"),
        ),
        migrations.AddField(
            model_name="feedback",
            name="phone_number",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Số điện thoại"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Mô tả"),
        ),
    ]
