# Generated by Django 4.2.3 on 2024-05-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0017_alter_feedback_options_alter_feedback_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người gửi",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="note",
            field=models.CharField(
                default="", max_length=500, verbose_name="Lí do duyệt"
            ),
        ),
    ]
