# Generated by Django 4.2.3 on 2024-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0018_alter_feedback_sender_alter_report_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
    ]
