# Generated by Django 4.2.3 on 2024-07-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0020_appconfig_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"verbose_name": "Tố cáo", "verbose_name_plural": "Tố cáo"},
        ),
    ]
