# Generated by Django 4.2.3 on 2024-07-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_alter_customuser_country"),
        ("general", "0021_alter_report_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProxy",
            fields=[],
            options={
                "verbose_name": "Admin",
                "verbose_name_plural": "Admin",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.customuser",),
        ),
    ]
