# Generated by Django 4.2.3 on 2024-07-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0023_backgroundcolor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundcolor",
            name="color",
            field=models.CharField(default="#FF0000", verbose_name="Mã màu"),
        ),
        migrations.AlterField(
            model_name="backgroundcolor",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
    ]
