# Generated by Django 4.2.3 on 2024-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0024_alter_backgroundcolor_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundcolor",
            name="title",
            field=models.CharField(default="Màu"),
        ),
    ]
