# Generated by Django 4.2.3 on 2024-07-19 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0026_cointrading_alter_backgroundcolor_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoneyTrading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("coin_price", models.PositiveIntegerField(default=0)),
                ("vnd_price", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
