# Generated by Django 4.2.3 on 2024-07-19 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0027_moneytrading"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIDTrading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("uid", models.CharField(max_length=8, verbose_name="UID")),
                (
                    "coin_price",
                    models.PositiveIntegerField(default=0, verbose_name="Số thóc"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "Hướng dẫn", "verbose_name_plural": "Hướng dẫn"},
        ),
        migrations.AlterModelOptions(
            name="backgroundcolor",
            options={
                "verbose_name": "Màu nền chat",
                "verbose_name_plural": "Màu nền chat",
            },
        ),
        migrations.AlterModelOptions(
            name="cointrading",
            options={
                "verbose_name": "Quy đổi tiền sang thóc",
                "verbose_name_plural": "Quy đổi tiền sang thóc",
            },
        ),
        migrations.AlterModelOptions(
            name="moneytrading",
            options={
                "verbose_name": "Quy đổi thóc sang tiền",
                "verbose_name_plural": "Quy đổi thóc sang tiền",
            },
        ),
        migrations.AlterField(
            model_name="cointrading",
            name="coin_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Số thóc"),
        ),
        migrations.AlterField(
            model_name="cointrading",
            name="vnd_price",
            field=models.PositiveIntegerField(default=0, verbose_name="VNĐ"),
        ),
        migrations.AlterField(
            model_name="moneytrading",
            name="coin_price",
            field=models.PositiveIntegerField(default=0, verbose_name="Số thóc"),
        ),
        migrations.AlterField(
            model_name="moneytrading",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Đang hoạt động"),
        ),
        migrations.AlterField(
            model_name="moneytrading",
            name="vnd_price",
            field=models.PositiveIntegerField(default=0, verbose_name="VNĐ"),
        ),
    ]
