# Generated by Django 4.2.3 on 2024-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0031_stickercategory_sticker_sticker_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="stickercategory",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
