# Generated by Django 4.2.3 on 2024-07-25 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0034_avatarframe"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppInformation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("instruction", "Hướng dẫn"),
                            ("aboutUs", "Về OCCO"),
                            ("rule", "Điều khoản đăng ký"),
                            ("appInfo", "Thông tin về ứng dụng"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thông tin ứng dụng",
                "verbose_name_plural": "Thông tin ứng dụng",
            },
        ),
    ]
