# Generated by Django 4.2.3 on 2024-07-25 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0035_appinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportAndTraining",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="assets/support-training/"
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hỗ trợ và đào tạo",
                "verbose_name_plural": "Hỗ trợ và đào tạo",
                "ordering": ["index"],
            },
        ),
    ]
