# Generated by Django 4.2.3 on 2024-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adstargeting",
            name="coin_price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="adstargeting",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adstargeting",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
