# Generated by Django 4.2.3 on 2024-07-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_adstargeting_coin_price_adstargeting_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="coin_price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
