# Generated by Django 4.2.3 on 2024-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_advertisement_coin_price_advertisement_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adstargeting", old_name="coin_price", new_name="count_click",
        ),
        migrations.RemoveField(model_name="adstargeting", name="end_time",),
        migrations.RemoveField(model_name="adstargeting", name="start_time",),
        migrations.AddField(
            model_name="adstargeting",
            name="count_view",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
