# Generated by Django 4.2.3 on 2024-07-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_rename_coin_price_adstargeting_count_click_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adstargeting",
            name="viewed_date",
            field=models.JSONField(default=dict),
        ),
    ]
