# Generated by Django 4.2.3 on 2024-07-31 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_adstargeting_viewed_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateCoinPerView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("coin", models.FloatField(default=0.1)),
                (
                    "description",
                    models.TextField(
                        default="Số thóc cho 1 lượt hiển thị đến người dùng"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="advertisement",
            name="maximum_view",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
