# Generated by Django 4.2.3 on 2024-07-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_ratecoinperview_advertisement_maximum_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="direct_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="maximum_view",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
