# Generated by Django 4.2.3 on 2024-07-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_alter_advertisement_direct_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="direct_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
