# Generated by Django 4.2.3 on 2024-08-01 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_remove_adstargeting_count_click_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdsWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_balance",
                    models.FloatField(default=0, verbose_name="Số dư ví"),
                ),
                ("previous_balance", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Ví QC", "verbose_name_plural": "Ví QC",},
        ),
        migrations.AlterModelOptions(
            name="ratecoinperview",
            options={
                "verbose_name": "Số thóc 1 lần xem/click",
                "verbose_name_plural": "Số thóc 1 lần xem/click",
            },
        ),
        migrations.AddField(
            model_name="advertisement",
            name="status_coming",
            field=models.CharField(
                choices=[
                    ("incoming", "Sắp diễn ra"),
                    ("coming", "Đang diễn ra"),
                    ("expired", "Hết hạn"),
                ],
                default="incoming",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="ratecoinperview",
            name="key",
            field=models.CharField(
                choices=[("view", "Xem"), ("click", "Click")],
                default="view",
                max_length=255,
            ),
        ),
    ]
