# Generated by Django 4.2.3 on 2024-08-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0011_adswallet_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="android_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="ios_url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[("ANDROID", "Android"), ("IOS", "iOS")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("USER", "Người dùng"),
                    ("WEB", "Web"),
                    ("APP", "App"),
                    ("DEFAULT", "Mặc định"),
                ],
                default="DEFAULT",
                max_length=255,
            ),
        ),
    ]
