# Generated by Django 4.2.3 on 2024-08-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0012_advertisement_android_url_advertisement_ios_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "verbose_name": "Danh sách quảng bá",
                "verbose_name_plural": "Danh sách quảng bá",
            },
        ),
    ]
