# Generated by Django 4.2.3 on 2024-08-05 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0037_vip_alter_appinformation_title_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0013_alter_advertisement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="android_url",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Android link"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="coin_price",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Số thóc"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="description",
            field=models.TextField(verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="direct_url",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Link chuyển hướng"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày kết thúc"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisement_image",
                to="general.fileupload",
                verbose_name="Ảnh",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="ios_url",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="IOS Link"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="note",
            field=models.TextField(
                blank=True, default="", verbose_name="Chú thích tới người dùng"
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày bắt đầu"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="status_coming",
            field=models.CharField(
                choices=[
                    ("incoming", "Sắp diễn ra"),
                    ("coming", "Đang diễn ra"),
                    ("expired", "Hết hạn"),
                ],
                default="incoming",
                max_length=10,
                verbose_name="Trạng thái diễn ra",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="status_verify",
            field=models.CharField(
                choices=[
                    ("pending", "Đợi duyệt"),
                    ("verified", "Đã duyệt"),
                    ("rejected", "Đã từ chối"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Trạng thái duyệt",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("USER", "Người dùng"),
                    ("WEB", "Web"),
                    ("APP", "App"),
                    ("DEFAULT", "Mặc định"),
                ],
                default="DEFAULT",
                max_length=255,
                verbose_name="Mục tiêu hướng đến",
            ),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Tiêu đề"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người tạo",
            ),
        ),
        migrations.AlterField(
            model_name="ratecoinperview",
            name="coin",
            field=models.FloatField(default=0.1, verbose_name="Số thóc"),
        ),
        migrations.AlterField(
            model_name="ratecoinperview",
            name="description",
            field=models.TextField(
                default="Số thóc cho 1 lượt hiển thị đến người dùng",
                verbose_name="Mô tả",
            ),
        ),
        migrations.AlterField(
            model_name="ratecoinperview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật vào"),
        ),
    ]
